<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
=======
'use client';

import { usePathname } from 'next/navigation';
import { Geist, Geist_Mono } from "next/font/google";
>>>>>>> 260e1cde52687c75c73fbb342c1bf109580c7129
import "./globals.css";

<<<<<<< HEAD
<<<<<<< HEAD
const inter = Inter({
  variable: "--font-inter",
=======
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

=======
>>>>>>> parent of 1274573 (Add New UI of landing page)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
>>>>>>> 5c90f1c201ecb0125b17314320968086e2ffd1b5
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

<<<<<<< HEAD
export const metadata: Metadata = {
<<<<<<< HEAD
<<<<<<< HEAD
  title: "Careon - Modern Nonprofit & Charity Platform",
  description: "Careon is a sleek, professional platform designed for nonprofits, foundations, and fundraising campaigns.",
=======
  title: "Careon - Modern Nonprofit & Charity Template",
  description: "Nonprofit and charity website",
>>>>>>> 5c90f1c201ecb0125b17314320968086e2ffd1b5
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> parent of 1274573 (Add New UI of landing page)
};

=======
>>>>>>> 260e1cde52687c75c73fbb342c1bf109580c7129
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAuthPage = pathname === '/login' || 
                     pathname === '/register' || 
                     pathname === '/forgot-password' || 
                     pathname === '/verify-otp' || 
                     pathname === '/reset-password';

  return (
<<<<<<< HEAD
<<<<<<< HEAD
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
=======
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white text-black overflow-x-hidden ${isAuthPage ? '' : 'pt-24'}`}>
        {!isAuthPage && <Navigation />}
        <main>
          {children}
        </main>
<<<<<<< HEAD
        <Footer />
>>>>>>> 5c90f1c201ecb0125b17314320968086e2ffd1b5
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> parent of 1274573 (Add New UI of landing page)
=======
        {!isAuthPage && <Footer />}
>>>>>>> 260e1cde52687c75c73fbb342c1bf109580c7129
      </body>
    </html>
  );
}
